### ISSUE TITLE
Help Wanted - Implementation in Angular

### ISSUE THREAD

**Issue by bkarv** [Amphiluke/floating-scroll#16]
Hi first of all fantastic plugin! I have an angular 6 project and would like to implement this. I do/can install JQUERY into my project but am struggling to implement this into my project. Have you had any experience using this in Angular? If so would it be possible to provide a working guide on how to implement it in an Angular project? Many thanks in advanced.

**Comment by Amphiluke** [comment]
Hi,

Unfortunately, I don’t have much experience in Angular. But if you don’t use jQuery in your project, I rather can suggest you to check out the [handy-scroll project](https://github.com/Amphiluke/handy-scroll) instead of this plugin. handy-scroll provides the very same functionality but it’s a _standalone_ widget and so it won’t bloat your project with huge dependencies like jQuery.

Also, you may find useful the discussion in [this issue](https://github.com/Amphiluke/handy-scroll/issues/1).

I believe, some day I’ll write a guide on using all this in Angular/Vue/React eventually. But probably it would be more appropriate to assemble separate framework-specific components on the base of this widget. Something like what the [angular-floatingscroll](https://www.npmjs.com/package/angular-floatingscroll) project does (unfortunately, it looks like it is not maintained anymore).

**Comment by Amphiluke** [comment]
I’ve written a [guide](https://github.com/Amphiluke/handy-scroll/blob/422e9a6ff3afb033a5e613184d5fb029a312011d/doc/angular-integration.md) on integration of the handy-scroll widget into an Angular app. Also, here is a [live demo](https://stackblitz.com/edit/angular-handy-scroll-integration) you may play with.

I’m closing the issue for now. Please feel free to re-open it if something goes wrong with those instructions. Or, if you finally decided to migrate to handy-scroll, better open a new issue in [that project](https://github.com/Amphiluke/handy-scroll).
