### ISSUE TITLE
floating scroll bar and actual scroll bar not in sync after couple of clicks

### ISSUE THREAD

**Issue by naitik95** [Amphiluke/floating-scroll#17]
Steps to reproduce on example#1 on demo page https://amphiluke.github.io/floating-scroll/

1) Scroll down just enough for floating scroll bar to surface
2) Click on right side of scroll bar to shift it to the right
3) Scroll down so that actual scroll bar surfaces
4) Click on left side of scroll bar to shift it to the left
5) Scroll up so that floating scroll bar surfaces
6) Click on right side of scroll bar to shift it to the right
7) Scroll down so that actual scroll bar surfaces

You should now see actual scroll bar still sitting on the left edge.

**Comment by Amphiluke** [comment]
Hello @naitik95 
Tried the steps you described but wasn’t able to reproduce the bug. Could you please provide a bit more info: what browser do you use and what OS? Also, is every widget affected or only some of them? Does the bug also appear for the minimum simplest setup?

**Comment by naitik95** [comment]
**Updated the wording in steps to reproduce**

Browser: Chrome Version 72
OS: Windows 7

I'm able to reproduce this on all 3 examples on the demo page. Same issue when I set it up in my application. I pulled up the code and changed syncContainer() to below and it worked:

`syncContainer(skipSyncWidget = false) {
    let instance = this;
    instance.skipSyncWidget = skipSyncWidget;
    if (instance.container.scrollLeft !== instance.widget.scrollLeft) {
      instance.container.scrollLeft = instance.widget.scrollLeft;
    }
  }`

**Comment by Amphiluke** [comment]
I managed to reproduce the bug in Firefox browser on Linux (tried catching it again on Windows but without success). The fix is now published in the plugin’s [new version 3.0.7](https://github.com/Amphiluke/floating-scroll/releases/tag/v3.0.7).

@naitik95, thanks for reporting! :+1: Could you please confirm that the bug has gone on Windows as well? You may check it on the same [demo page](https://amphiluke.github.io/floating-scroll/?v3.0.7) but please be sure to clear browser cache, just in case.

**Comment by naitik95** [comment]
yep, fixed, thank you. And thank you for making this insanely helpful plugin.
